export const GET_MAIN_PRODUCT = 'GET_MAIN_PRODUCT';
export const GET_MAIN_PRODUCT_SUCCESS = 'GET_MAIN_PRODUCT_SUCCESS';
export const GET_MAIN_PRODUCT_FAILED = 'GET_MAIN_PRODUCT_FAILED';

export const GET_MAIN_PRODUCT_DETAIL = 'GET_MAIN_PRODUCT_DETAIL';
export const GET_MAIN_PRODUCT_DETAIL_SUCCESS =
  'GET_MAIN_PRODUCT_DETAIL_SUCCESS';
export const GET_MAIN_PRODUCT_DETAIL_FAILED = 'GET_MAIN_PRODUCT_DETAIL_FAILED';

export const POST_MAIN_PRODUCT = 'POST_MAIN_PRODUCT';
export const POST_MAIN_PRODUCT_SUCCESS = 'POST_MAIN_PRODUCT_SUCCESS';
export const POST_MAIN_PRODUCT_FAILED = 'POST_MAIN_PRODUCT_FAILED';

export const DELETE_MAIN_PRODUCT = 'DELETE_MAIN_PRODUCT';
export const DELETE_MAIN_PRODUCT_SUCCESS = 'DELETE_MAIN_PRODUCT_SUCCESS';
export const DELETE_MAIN_PRODUCT_FAILED = 'DELETE_MAIN_PRODUCT_FAILED';

export const EDIT_MAIN_PRODUCT = 'EDIT_MAIN_PRODUCT';
export const EDIT_MAIN_PRODUCT_SUCCESS = 'EDIT_MAIN_PRODUCT_SUCCESS';
export const EDIT_MAIN_PRODUCT_FAILED = 'EDIT_MAIN_PRODUCT_FAILED';
