export const GET_MAIN_PRODUCT = 'GET_MAIN_PRODUCT';
export const GET_MAIN_PRODUCT_SUCCESS = 'GET_MAIN_PRODUCT_SUCCESS';
export const GET_MAIN_PRODUCT_FAILED = 'GET_MAIN_PRODUCT_FAILED';

export const POST_MAIN_PRODUCT = 'POST_MAIN_PRODUCT';
export const POST_MAIN_PRODUCT_SUCCESS = 'POST_MAIN_PRODUCT_SUCCESS';
export const POST_MAIN_PRODUCT_FAILED = 'POST_MAIN_PRODUCT_FAILED';
